version = 0.1
[default.deploy.parameters]
stack_name = "data-transformation-exp"
resolve_s3 = true
s3_prefix = "data-transformation-exp"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
